export const categories = [
  "Music",
  "Entertainment",
  "Gaming",
  "Sports",
  "Education",
  "Science & Technology",
  "Comedy",
  "Beauty & Fashion",
  "Food & Cooking",
  "Travel & Events",
  "Health & Fitness",
  "News & Politics",
  "Kids",
  "Animals & Pets",
  "Autos & Vehicles",
  "Business & Finance",
  "Spiritual & Wellness",
  "Art & Design",
  "Films & Animation",
];
